### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Bendenice**
ckeditor 4.5.11 + kceditor

### CODE REVIEW

**Comment by Bendenice** [comment]
Last version of ckeditor 4.5.11 + KCFinder

**Comment by mambax7** [comment]
The CKEditor should go here:
https://github.com/XoopsModules25x/xoopseditors/tree/master/htdocs/class/xoopseditor/ckeditor

Can you fix it?

**Comment by Bendenice** [comment]
Sorry I really understand nothing with github and tutorials really do not help me :-/

**Comment by mambax7** [comment]
OK, I'll fix it. 
If you have questions about GitHub, just ask, and we'll be glad to help...

**Pull request merged**
